---
title: "**Functional Specialization (FSpe)**"
output: html_document
---
\ 

***

\ 

<font size=3> Packages:
```{r warning = FALSE, message = FALSE}
library(ggeasy)
library(tibble)
library(ape)
library(cluster)	
library(ggplot2)
library(extrafont)
```

# **Interspecific**

<font size=3> Load data:
```{r}
data(iris)
```

<font size=3> Standardize + Create a distance matrix + PCoA:
```{r}
PCOA <- iris[,1:4] %>%  scale() %>%  daisy(metric="euclidean") %>% pcoa(correction="cailliez")
```

<font size=3> Extract the two first PCoA axes:
```{r}
Axes<-PCOA$vectors[,1:2] %>% as.data.frame() %>% add_column(Species = iris[,5], .before = 1)
```

<font size=3> Extract data centroid + Index generation:
```{r warning = FALSE}
o<-apply(Axes[,2:3],	2,	mean) %>% rbind() %>% as.data.frame()
```

<font size=3> Index generation:
```{r}
speS<-Axes[,2:3] %>% apply(1,	function(x)	{	(sum((x-o)^2)	)^0.5}) %>% as.data.frame()
```

<font size=3> Plot:
```{r}
PC<-data.frame(PCoA1 = PCOA$vectors[,1], PCoA2 = PCOA$vectors[,2]) %>% #Plot
  add_column(Species = iris[,5], .before = 1)

A<-ggplot(data = PC, aes(PCoA1, PCoA2))+  #plot
  geom_segment(data = Axes,
    aes(x = -3.082387e-18, y = 2.333830e-16, xend = Axis.1, yend = Axis.2), colour = "grey", size = 0.3)+
  geom_point(aes(x = -3.082387e-18, y = 2.333830e-16), 
    fill = "#FFFFFF", colour = "grey", size = 3, shape = 21, stroke=0.5)+
  geom_point(data = PC,aes(group= Species, fill = Species), size=5, shape = 21, stroke=1.1)+
  scale_fill_manual(values = c("#F29783", "#B5F252","#A2A0F0"))+
  labs(title = "Interspecific", x = "PCoA1 (72.9%)", y = "PCoA2 (22.8%)")+
  ggeasy::easy_center_title()+
  coord_fixed()+
  theme(plot.title = element_text(face = "bold",size = 22))+
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black"))+
  theme(axis.text=element_text(size=16),
        axis.title=element_text(size=16))+
  theme(
    legend.text = element_text(size=11.5),
    legend.title = element_text(size=14),
    legend.position = c(0.845, 1),
    legend.justification = c("left", "top"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6),
    legend.key.size = )+
  theme(text=element_text(family="Times New Roman"))+
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5))
A
```

